### ISSUE TITLE
TypeError: request() got an unexpected keyword argument 'prefetch

### ISSUE THREAD

**Issue by cypreess** [kennethreitz/stathat.py#5]
Trying the demo code from README and got:

```
>>> stats.count('wtfs/minute', 10)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/stathat.py", line 48, in count
    r = self._http_post('/ez', {'email': self.email, 'stat': key, 'count': count})
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/stathat.py", line 40, in _http_post
    r = self.session.post(url, data=data, prefetch=True)
  File "/usr/local/Cellar/python/2.7.4/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests/sessions.py", line 425, in post
    return self.request('POST', url, data=data, **kwargs)
TypeError: request() got an unexpected keyword argument 'prefetch
```

**Comment by muminoff** [comment]
Same here.

**Comment by kennethreitz** [comment]
fixed!

**Comment by muminoff** [comment]
@kennethreitz :+1:
